# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
lang: en-US
title: Anson Liu
email: anson@ansonliu.com
description: Code . Run . Eat . Sleep ↺
baseurl: ""
url: "http://ansonliu.com"
author:
  name: Anson Liu
  picture: https://avatars1.githubusercontent.com/ansonl?v=3&s=200
github_username: ansonl
logo: # path of site logo, e.g. "/assets/images/logo.png"

#Custom settings
permalink: /:year/:month/:title/
google_analytics: UA-55429613-1
disqus:
  shortname: apparentetch

# Build settings
markdown: kramdown
highlighter: rouge

#kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-avatar
  - jekyll-gist


feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: /page:num/

# Front Matter Defaults
defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      read_time: true
